name: Build Dia Windows (.exe)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configurar MSYS2 no GitHub
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-toolchain
          mingw-w64-ucrt-x86_64-gtk3
          mingw-w64-ucrt-x86_64-meson
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-libxml2

    - name: Compilar o Dia
      shell: msys2 {0}
      run: |
        meson setup build-win
        ninja -C build-win

    - name: Compactar o executável gerado
      shell: msys2 {0}
      run: |
        cd build-win/app
        zip -r dia-windows.zip .

    - name: Disponibilizar para Download
      uses: actions/upload-artifact@v4
      with:
        name: Dia-Windows-Exe
        path: build-win/app/dia-windows.zip
